services:
    bovbackend:
      container_name: bov_app
      build: 
        context: ./server
      ports:
        - "3000:3000"
      networks:
            - bov-network
      env_file:
          - ./server/.env
      command: npm start

networks:
    bov-network:
        name: bov-network